### ISSUE TITLE
General - accordion click should be easier

### ISSUE THREAD

**Issue by thurston-ssa** [dsheashea/Final-Project#10]
There are multiple views that use accordion-style lists, where you click on a list item and it slides down to reveal more detail;
for those views, it should be easier to expand the detail; shouldn't need to just click on the narrow text label, should be able to click anywhere on the item.

See research, update workout history, regimen (probably other places as well)

@theshahofny @jbrown762 @dsheashea

**Comment by dsheashea** [comment]
Accepted:
@thurston-ssa  Updated the pointer, the click on the exercises, and update history pages..

**Comment by thurston-ssa** [comment]
verified that this is fixed on research and log workout views

@dsheashea
