### ISSUE TITLE
Research View - exercise detail popup

### ISSUE THREAD

**Issue by thurston-ssa** [dsheashea/Final-Project#13]
Secondly, the close box isn't visible, so there is no way to dismiss the modal; 
should be able to just click anywhere outside the modal (in the semi-transparent screen) to dismiss the modal and/or hit the esc key to dismiss it.

@dsheashea

**Comment by theshahofny** [comment]
accepted

**Comment by dsheashea** [comment]
@thurston-ssa ready to verified

**Comment by thurston-ssa** [comment]
Verified/Closing
