### ISSUE TITLE
Calendar - show context sensitive tooltip for individual days

### ISSUE THREAD

**Issue by thurston-ssa** [dsheashea/Final-Project#16]
For days that are "clickable" - should have a context-sensitive tooltip that indicates to the user what clicking on the day does:
for "active" days - "View Workout Details"
for "inactive" days - "Log Your Workout"
for days that aren't clickable (i.e. days in the future,) the cursor shouldn't change to the pointer, but should remain the default - because clicking doesn't do anything for future days

@theshahofny

**Comment by theshahofny** [comment]
accepted @thurston-ssa

**Comment by theshahofny** [comment]
@thurston-ssa ready to be verified

**Comment by thurston-ssa** [comment]
verified/closing
