### ISSUE TITLE
Workout Detail - 

### ISSUE THREAD

**Issue by thurston-ssa** [dsheashea/Final-Project#18]
The workout detail should:

- display the date (imagine, user goes and gets a coffee, how can they know what date they're looking at?
- not show label "Time" when it's a weight-based exercise; yes, it's empty, but the label shouldn't show at all (notice that duration doesn't show, just time)
- "weight" shows up twice (at least for weight-based exercises):  see 5 October for an example

@theshahofny

**Comment by theshahofny** [comment]
@thurston-ssa  ready to be verified

**Comment by thurston-ssa** [comment]
verified/closing
