### ISSUE TITLE
Log Workout - Hide right-side controls until exercise selected (feature)

### ISSUE THREAD

**Issue by thurston-ssa** [dsheashea/Final-Project#22]
When a user first goes to add a new exercise history - the right hand side controls should be hidden until they have chosen an exercise; currently it defaults to weight/rep/sets, but that isn't proper context for cardio exercises; it would be better if you would just show the right side once an exercise is selected (you already have logic for selecting which set is appropriate).

Also, change the order of the weight:reps:sets to reps:sets:weight (weight is "overloaded" so provide it more context by making it last)

@dsheashea

**Comment by dsheashea** [comment]
@thurston-ssa ready for verification

**Comment by thurston-ssa** [comment]
verified
