### ISSUE TITLE
Log Workout - Transition after successful save

### ISSUE THREAD

**Issue by thurston-ssa** [dsheashea/Final-Project#23]
When a user saves their workout day, two things should happen:

- there should be a temporary "modal" message, "your workout has saved" - it can fade out within a few seconds

- there should be a transition back to the workout calendar (selecting the appropriate month as the target, i.e. the month of the day they just saved)

it is extremely important to give visual indicators to users - otherwise they tend to think nothing happened, will try again, etc.

@dsheashea

**Comment by dsheashea** [comment]
@thurston-ssa Ready for verification. A successful post will now display a success message and timeout to transition to calendar

**Comment by thurston-ssa** [comment]
can you make the timeout longer?  if I didn't know to look for it (the success message), i would have missed it.

@dsheashea

**Comment by dsheashea** [comment]
@thurston-ssa accepted

**Comment by dsheashea** [comment]
@thurston-ssa ready to be verified

**Comment by thurston-ssa** [comment]
success message ok now, but transition doesn't take you back to proper month
to test, choose some prior month/date (June 12th is good), add & save a workout;
success message
transition to monthly calendar --> October
still open

**Comment by dsheashea** [comment]
@thurston-ssa ready to be verified

**Comment by thurston-ssa** [comment]
Verified/closed
