### ISSUE TITLE
Workout Calendar - **Why is there a square at bottom in its own row?**

### ISSUE THREAD

**Issue by thurston-ssa** [dsheashea/Final-Project#26]
High priority fix

<img width="960" alt="wc-bottom" src="https://cloud.githubusercontent.com/assets/22619446/19627422/74209d7e-9914-11e6-844c-99239f4814db.png">

@theshahofny

**Comment by dsheashea** [comment]
@thurston-ssa accepted and ready to be verified

**Comment by thurston-ssa** [comment]
verified  fixed
