### ISSUE TITLE
Regimen view - adding an exercise

### ISSUE THREAD

**Issue by thurston-ssa** [dsheashea/Final-Project#7]
When adding a new regimen exercise to an extant regimen, the new exercise should slot-in in proper order (currently it is always appended to the end of the list), so e.g.  a Wednesday exercise should appear grouped with any other Wednesday exercises.

Also, should be styled differently to distinguish it from the extant regimen exercises, so I can visually see that this is a new exercise

Assigned To: Joe

**Comment by jbrown762** [comment]
accepted

**Comment by jbrown762** [comment]
@thurston-ssa ready for verification. the added exercises are not sorted by day but are still grouped together

**Comment by thurston-ssa** [comment]
so i can confirm that they are grouped together and it's easy to spot them, but they should be in daily order - so i'm leaving the issue open

**Comment by jbrown762** [comment]
@thurston-ssa days now sorted in order. ready for verification.

**Comment by thurston-ssa** [comment]
Verified/Closing - looks good
