### ISSUE TITLE
Regimen View - Black Text Against A Black Background

### ISSUE THREAD

**Issue by thurston-ssa** [dsheashea/Final-Project#8]
TSSIA

Assigned To: Joe

**Comment by dsheashea** [comment]
@thurston-ssa accepted

**Comment by jbrown762** [comment]
@thurston-ssa black text on regimen detail/create/update views has been fixed

**Comment by thurston-ssa** [comment]
verified (although when i click on Regimen in nav bar, it briefly flashes and shows the old black-on-black)
