### ISSUE TITLE
Regimen View - Distinguish Active From Inactive Days

### ISSUE THREAD

**Issue by thurston-ssa** [dsheashea/Final-Project#9]
It's awkward to use the regimen view when you have an existing regimen.
You have to click on each day to see what your regimen is;  
at minimum should highlight those days with some exercises from those without; simplest way would be to mark the day text in green (for active); or could change the background color.

In addition, should be some sort of link to "expand all", which would expand all the days with at least one exercise; it's too much work to just see what your regimen is.

Assigned to: @jbrown762

**Comment by jbrown762** [comment]
@thurston-ssa current day is now highlighted in green.
The expand/collapse all button is giving me a lot of trouble. not sure if/how we can make the button work with the current code

**Comment by jbrown762** [comment]
@thurston-ssa 

The regimen view has been updated away from the accordion view so no Expand All button will be added.

Days with workouts are highlighted in green. Ready for verification.

**Comment by thurston-ssa** [comment]
verified/closing
